title: Ally Rice
description: Technical & Scientific Writer
site_title: 'Ally Rice'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: alrice12
# blog_url: https://www.nagekar.com
email: ally.c.rice@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 